### ISSUE TITLE
Logging entries have incorrect trace

### ISSUE THREAD

**Issue by pkarolis** [micronaut-projects/micronaut-gcp#479]
### Expected Behavior

Logging entries from the same request ID should be grouped by trace id. 

### Actual Behaviour

My first logging entry which is HTTP request get this trace id:
trace: "projects/{projectId}/traces/5815f70dd8c064c73a73f2c8a3652e0c"
the subsequent two logging entries get a different trace id:
trace: "5815f70dd8c064c73a73f2c8a3652e0c"
and 
trace: "5815f70dd8c064c73a73f2c8a3652e0c"

This i believe leads to logs not being grouped together by parent child. 

### Steps To Reproduce

Running with     micronaut-gcp-logging and micronaut-gcp-tracing in the pom. application properties also have tracing:zipkin:enabled: true

### Environment Information

appengine standard java 11

micronaut-gcp-logging 4.0.0

### Version

3.0.0

**Comment by Praytic** [comment]
These two trace IDs are identical.

**Comment by graemerocher** [comment]
Provide an example that reproduces the issue

**Comment by fromlabs** [comment]
I've the same problem, it's not easy to reproduce because of the gcp project setup.
@Praytic 
trace: `"projects/{projectId}/traces/5815f70dd8c064c73a73f2c8a3652e0c"`
and
trace: `"5815f70dd8c064c73a73f2c8a3652e0c"`
have the same `traceId` but aren't formatted equally.
I've debugged my appllication and I've found that `io.micronaut.gcp.logging.StackdriverJsonLayout` handles the "GCP trace format" thanks to `StackdriverTraceConstants.composeFullTraceName()` but is conditioned to a properly configured `projectId`:
```java
private void addTraceId(ILoggingEvent event, Map<String, Object> map) {
    if (!this.includeTraceId) {
        return;
    }
    String traceId =
            event.getMDCPropertyMap().get(StackdriverTraceConstants.MDC_FIELD_TRACE_ID);
    if (!StringUtils.isEmpty(traceId)
            && !StringUtils.isEmpty(this.projectId)
            && !this.projectId.endsWith("_IS_UNDEFINED")) {
        traceId = StackdriverTraceConstants.composeFullTraceName(
                this.projectId, formatTraceId(traceId));
    }

    add(StackdriverTraceConstants.TRACE_ID_ATTRIBUTE, this.includeTraceId, traceId, map);
}
```
In my application `this.projectId` is equal to `projectId_IS_UNDEFINED` because I'm using the "detected gcp project id mode".

> You can inject this bean and use the getProjectId() method to retrieve the configured or detected project ID.

The full format trace mode is skipped because of the `!StringUtils.isEmpty(this.projectId) && !this.projectId.endsWith("_IS_UNDEFINED")` condition.

And this is fine for me but why `projectId` isn't detected from my environment? The `logback-json-appender.xml` uses a ${projectId} placeholder but I don't think it's working properly:
```xml
<appender name="CONSOLE_JSON" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="io.micronaut.gcp.logging.StackdriverJsonLayout">
                <projectId>${projectId}</projectId>
                ...
```
Lastly I found that `io.micronaut.gcp.logging.StackdriverJsonLayout` has an error in the `start()` method preventing initializing `projectId` in the "detected mode":

```java
@Override
public void start() {
    super.start();
    // If no Project ID set, then attempt to resolve it with the default project ID provider
    if (StringUtils.isEmpty(this.projectId)) {
        this.projectId = ServiceOptions.getDefaultProjectId();
    }
}
```
Debugging my application `ServiceOptions.getDefaultProjectId()` returns the right project id but the assignment is skipped because `this.projectId` is not `null` but equal to `projectId_IS_UNDEFINED` as before but the condition misses the `_IS_UNDEFINED` check. 
As we seen before comparing with the `StackdriverJsonLayout.addTraceId()` method, I think the right condition should be `StringUtils.isEmpty(this.projectId) || this.projectId.endsWith("_IS_UNDEFINED")`.

**Comment by graemerocher** [comment]
@fromlabs seems you have debugged the problem and provided some nice insight. Would you like to send a PR?
